<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\City;
use App\Models\LocationMaster;
use App\Models\MarketingAgent;
use App\Models\Project;
use App\Models\Blog;
use App\Models\GalleryItem;
use App\Models\Enquiry;
use App\Models\JobApplication;
use App\Models\Document;
use App\Models\SiteVisit;
use App\Models\Wallet;
use App\Models\WalletTransaction;
use App\Models\Customer;
use App\Models\Supplier;
use App\Models\InventoryItem;
use App\Models\StockMovement;
use App\Models\ExpenseCategory;
use App\Models\Expense;
use App\Models\Quotation;
use App\Models\Invoice;
use App\Models\Loan;
use App\Models\LoanPayment;
use App\Models\PaymentIn;
use App\Models\PaymentOut;
use App\Models\AccountingActivity;
use App\Models\CostAnalysis;
use App\Models\ProjectInspection;

class DemoDataSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Cities
        if (City::count() === 0) {
            City::insert([
                ['id' => 'city-1', 'name' => 'Visakhapatnam', 'state' => 'Andhra Pradesh', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'city-2', 'name' => 'Hyderabad', 'state' => 'Telangana', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'city-3', 'name' => 'Vijayawada', 'state' => 'Andhra Pradesh', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'city-4', 'name' => 'Guntur', 'state' => 'Andhra Pradesh', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'city-5', 'name' => 'Tirupati', 'state' => 'Andhra Pradesh', 'created_at' => now(), 'updated_at' => now()],
            ]);
        }

        // 2. Location Masters
        if (LocationMaster::count() === 0) {
            LocationMaster::insert([
                ['id' => 'loc-1', 'name' => 'Madhurawada', 'cityId' => 'city-1', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'loc-2', 'name' => 'Rushikonda Beach Road', 'cityId' => 'city-1', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'loc-3', 'name' => 'MVP Colony', 'cityId' => 'city-1', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'loc-4', 'name' => 'Gachibowli Financial District', 'cityId' => 'city-2', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'loc-5', 'name' => 'Jubilee Hills', 'cityId' => 'city-2', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'loc-6', 'name' => 'Benz Circle', 'cityId' => 'city-3', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'loc-7', 'name' => 'Amaravati Express Highway', 'cityId' => 'city-4', 'created_at' => now(), 'updated_at' => now()],
            ]);
        }

        // 3. Marketing Agents
        if (MarketingAgent::count() === 0) {
            MarketingAgent::insert([
                [
                    'id' => 'ag-1',
                    'name' => 'Rajesh Varma',
                    'phone' => '+91 9848022334',
                    'email' => 'rajesh.varma@apexinfra.com',
                    'designation' => 'Senior Property Advisor',
                    'agencyName' => 'Apex Infra Direct Sales',
                    'reraNumber' => 'AP RERA/AG/15002',
                    'status' => 'Active',
                    'photoUrl' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=300&q=80',
                    'notes' => 'Handling Visakhapatnam luxury high-rise portfolio & villa sales.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'ag-2',
                    'name' => 'Priya Sharma',
                    'phone' => '+91 9701044556',
                    'email' => 'priya.sharma@apexinfra.com',
                    'designation' => 'Luxury Residential Consultant',
                    'agencyName' => 'Apex Premier Estates',
                    'reraNumber' => 'TS RERA/AG/24018',
                    'status' => 'Active',
                    'photoUrl' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
                    'notes' => 'Handling Hyderabad Financial District premium inquiries.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'ag-3',
                    'name' => 'K. Venkat Rao',
                    'phone' => '+91 9989077889',
                    'email' => 'venkat.rao@apexinfra.com',
                    'designation' => 'Plots & Commercial Manager',
                    'agencyName' => 'Apex Land Capital',
                    'reraNumber' => 'AP RERA/AG/19082',
                    'status' => 'Active',
                    'photoUrl' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
                    'notes' => 'Specialist in CRDA approved layouts and commercial spaces.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 4. Projects (Ongoing, Upcoming, Completed, Sites / Plotting, Marketing)
        if (Project::count() === 0) {
            $projectsData = [
                [
                    'id' => 'proj-1',
                    'name' => 'Apex One Heights',
                    'category' => 'Ongoing',
                    'subCategory' => 'Luxury High-Rise Apartments',
                    'status' => 'Ongoing',
                    'location' => 'Madhurawada, Visakhapatnam',
                    'city' => 'Visakhapatnam',
                    'microLocation' => 'Near IT SEZ, Madhurawada',
                    'description' => 'Apex One Heights is a landmark luxury residential high-rise featuring 3 & 4 BHK sky-residences. Engineered with seismic-resistant Mivan aluminum formwork technology, expansive private sundeck balconies overlooking scenic hill greenery, and over 40+ world-class lifestyle amenities.',
                    'overview' => 'G+18 Floors Luxury Tower with 120 vastu-compliant units, 70% open green landscaped grounds, infinity rooftop swimming pool, and 3-tier smart security.',
                    'price' => 8500000,
                    'priceRange' => '₹85.0 L - ₹1.45 Cr',
                    'priceValue' => 8500000,
                    'area' => '1,750 - 2,650 Sq.Ft',
                    'facing' => 'East, North',
                    'propertyType' => '3 BHK, 4 BHK',
                    'floors' => 18,
                    'unitsCount' => 120,
                    'reraNumber' => 'AP RERA: P03280014522',
                    'featured' => true,
                    'isMarketing' => false,
                    'images' => json_encode([
                        'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
                        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
                        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
                        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
                    ]),
                    'amenities' => json_encode(['Clubhouse', 'Swimming Pool', 'Gymnasium', '24/7 Security', 'Children Play Area', 'Landscaped Gardens', 'Power Backup', 'EV Charging Station']),
                    'specifications' => json_encode([
                        ['category' => 'Structure', 'details' => 'R.C.C. shear wall framed structure resistant to wind & earthquake (Zone III).'],
                        ['category' => 'Flooring', 'details' => '800x1200mm Premium glazed vitrified tiles in living, dining & master bedroom.'],
                        ['category' => 'Doors & Windows', 'details' => 'Teak wood main frame with designer shutter, UPVC sliding doors with mosquito mesh.'],
                        ['category' => 'Electrical', 'details' => 'Concealed copper wiring with Schneider modular switches, EV charging point.'],
                    ]),
                    'timeline' => json_encode([
                        ['phase' => 'Excavation & Piling', 'date' => 'Completed Q1 2025', 'status' => 'Completed'],
                        ['phase' => 'Basement & Podium Slab', 'date' => 'Completed Q3 2025', 'status' => 'Completed'],
                        ['phase' => 'Superstructure Slabs (G+18)', 'date' => 'In Progress (85%)', 'status' => 'In Progress'],
                        ['phase' => 'Interior Finishing & Handover', 'date' => 'Target Q4 2026', 'status' => 'Upcoming'],
                    ]),
                    'paymentPlans' => json_encode([
                        ['milestone' => 'On Booking Application', 'percentage' => 10],
                        ['milestone' => 'On Agreement Execution', 'percentage' => 15],
                        ['milestone' => 'On Completion of Ground Slab', 'percentage' => 15],
                        ['milestone' => 'On Floor-wise Slab Progress', 'percentage' => 40],
                        ['milestone' => 'On Handover & Registration', 'percentage' => 20],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'proj-2',
                    'name' => 'Apex Boulevard Villas',
                    'category' => 'Ongoing',
                    'subCategory' => 'Luxury Gated Villas',
                    'status' => 'Ongoing',
                    'location' => 'Rushikonda Beach Road, Visakhapatnam',
                    'city' => 'Visakhapatnam',
                    'microLocation' => 'Beachside Scenic Strip, Rushikonda',
                    'description' => 'A master-planned enclave of 48 signature Triplex Luxury Villas on the sun-kissed coast of Rushikonda. Every villa is crafted with a private heated plunge pool, dedicated hydraulic home elevator, expansive double-height lounge, and private terrace garden.',
                    'overview' => 'Triplex Luxury Villas with 3,400 to 4,800 Sft built-up area on 300 to 500 Sq.Yard individual plots with 100% sea breeze and private clubhouse access.',
                    'price' => 24000000,
                    'priceRange' => '₹2.25 Cr - ₹3.80 Cr',
                    'priceValue' => 24000000,
                    'area' => '3,400 - 4,800 Sq.Ft',
                    'facing' => 'East, North-East',
                    'propertyType' => 'Villa',
                    'floors' => 3,
                    'unitsCount' => 48,
                    'reraNumber' => 'AP RERA: P03280018944',
                    'featured' => true,
                    'isMarketing' => false,
                    'images' => json_encode([
                        'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
                        'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
                        'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
                    ]),
                    'amenities' => json_encode(['Clubhouse', 'Swimming Pool', 'Gymnasium', '24/7 Security', 'Children Play Area', 'Landscaped Gardens', 'Private Plunge Pool']),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'proj-3',
                    'name' => 'Apex Crystal Towers',
                    'category' => 'Upcoming',
                    'subCategory' => 'Ultra-Luxury Tech Homes',
                    'status' => 'Upcoming',
                    'location' => 'Financial District, Gachibowli, Hyderabad',
                    'city' => 'Hyderabad',
                    'microLocation' => 'Near Nanakramguda Circle',
                    'description' => 'Apex Crystal Towers is our upcoming flagship landmark at the epicentre of Hyderabad\'s financial district. Boasting panoramic sky views, AI-assisted energy automation, sound-dampened acoustic walls, and a 45,000 Sft sky club.',
                    'overview' => 'Twin 32-Storey architectural towers featuring 2, 3 & 4 BHK apartments with biometric smart entry and high-speed OTIS elevators.',
                    'price' => 12000000,
                    'priceRange' => '₹1.20 Cr - ₹2.50 Cr',
                    'priceValue' => 12000000,
                    'area' => '1,650 - 3,200 Sq.Ft',
                    'facing' => 'East, West',
                    'propertyType' => '2 BHK, 3 BHK, 4 BHK',
                    'floors' => 32,
                    'unitsCount' => 240,
                    'reraNumber' => 'TS RERA: P02400006789',
                    'featured' => true,
                    'isMarketing' => false,
                    'images' => json_encode([
                        'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
                        'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f6?auto=format&fit=crop&w=1200&q=80',
                    ]),
                    'amenities' => json_encode(['Clubhouse', 'Swimming Pool', 'Gymnasium', '24/7 Security', 'EV Charging Station', 'Infinity Rooftop Deck']),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'proj-4',
                    'name' => 'Apex Green Valley',
                    'category' => 'Completed',
                    'subCategory' => 'Gated Society',
                    'status' => 'Completed',
                    'location' => 'MVP Colony, Visakhapatnam',
                    'city' => 'Visakhapatnam',
                    'microLocation' => 'Sector 8, MVP Colony',
                    'description' => 'Completed and handed over ahead of schedule. A vibrant residential community of 80 happy families enjoying 100% power backup, fully functional clubhouse, children play park, and round-the-clock water supply.',
                    'overview' => 'Delivered G+5 floors society with 100% occupancy and clear legal documentation.',
                    'price' => 7500000,
                    'priceRange' => 'Sold Out (Delivered)',
                    'priceValue' => 7500000,
                    'area' => '1,450 - 2,100 Sq.Ft',
                    'facing' => 'North, East',
                    'propertyType' => '2 BHK, 3 BHK',
                    'floors' => 5,
                    'unitsCount' => 80,
                    'reraNumber' => 'AP RERA: P03280009123',
                    'featured' => false,
                    'isMarketing' => false,
                    'images' => json_encode([
                        'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
                        'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
                    ]),
                    'amenities' => json_encode(['Clubhouse', 'Gymnasium', '24/7 Security', 'Children Play Area', 'Power Backup']),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'proj-5',
                    'name' => 'Apex Capital City Open Plots',
                    'category' => 'Sites',
                    'subCategory' => 'CRDA Approved Plots',
                    'status' => 'Ongoing',
                    'location' => 'Amaravati Express Highway, Guntur',
                    'city' => 'Amaravati',
                    'microLocation' => 'Amaravati Growth Corridor',
                    'description' => 'CRDA Approved premium mega layout featuring 60-ft and 40-ft wide blacktop roads, underground electricity cabling, underground drainage, avenue plantations, and instant title spot registration.',
                    'overview' => '100% Vastu-compliant layout spanning 25 acres with immediate bank loan assistance and high expected capital appreciation.',
                    'price' => 28000,
                    'priceRange' => '₹28,000 / Sq.Yard',
                    'priceValue' => 28000,
                    'area' => '180 - 500 Sq.Yards',
                    'facing' => 'East, North, West',
                    'propertyType' => 'Plots',
                    'classification' => 'CRDA Approved',
                    'featured' => true,
                    'isMarketing' => false,
                    'images' => json_encode([
                        'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
                        'https://images.unsplash.com/photo-1524813686514-a57563d77d66?auto=format&fit=crop&w=1200&q=80',
                    ]),
                    'amenities' => json_encode(['24/7 Security', 'Compound Wall', 'Underground Drainage', 'Avenue Plantation', 'Electricity & Streetlights']),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'proj-6',
                    'name' => 'Apex Aero View Enclave',
                    'category' => 'Sites',
                    'subCategory' => 'DTCP Approved Plots',
                    'status' => 'Ongoing',
                    'location' => 'Bhogapuram International Airport Highway',
                    'city' => 'Visakhapatnam',
                    'microLocation' => 'Adjacent to 6-Lane Highway',
                    'description' => 'High-appreciation residential open plots located just 10 minutes from the upcoming Bhogapuram Greenfield International Airport. Clear title, gated compound wall, landscaped central park, and dedicated water line to every plot.',
                    'overview' => 'DTCP & RERA approved layout ideal for immediate residential villa construction or long-term investment holding.',
                    'price' => 18500,
                    'priceRange' => '₹18,500 / Sq.Yard',
                    'priceValue' => 18500,
                    'area' => '150 - 400 Sq.Yards',
                    'facing' => 'East, North',
                    'propertyType' => 'Plots',
                    'classification' => 'DTCP Approved',
                    'featured' => true,
                    'isMarketing' => false,
                    'images' => json_encode([
                        'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
                        'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
                    ]),
                    'amenities' => json_encode(['24/7 Security', 'Compound Wall', 'Underground Drainage', 'Street Lighting', 'Parks & Playgrounds']),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'proj-7',
                    'name' => 'Apex Horizon Commercial Plaza',
                    'category' => 'Ongoing',
                    'subCategory' => 'Grade-A Commercial Space',
                    'status' => 'Ongoing',
                    'location' => 'Benz Circle, Vijayawada',
                    'city' => 'Vijayawada',
                    'microLocation' => 'Benz Circle Prime Corner',
                    'description' => 'Grade-A corporate office suites, retail flagship stores, and rooftop dining venues at Vijayawada\'s most commanding commercial junction. Generates high footfalls, guaranteed brand visibility, and attractive rental yields.',
                    'overview' => 'B+G+10 Commercial Tower with automated multi-level car parking, high-speed capsule elevators, and LEED Green Building certification.',
                    'price' => 6500000,
                    'priceRange' => '₹65.0 L - ₹3.2 Cr',
                    'priceValue' => 6500000,
                    'area' => '650 - 4,500 Sq.Ft',
                    'facing' => 'North, East',
                    'propertyType' => 'Commercial',
                    'floors' => 10,
                    'unitsCount' => 60,
                    'reraNumber' => 'AP RERA: P06180004561',
                    'featured' => true,
                    'isMarketing' => true,
                    'images' => json_encode([
                        'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
                        'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
                    ]),
                    'amenities' => json_encode(['24/7 Security', 'Power Backup', 'Capsule Elevators', 'Multi-level Parking', 'Central Air Conditioning']),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ];

            foreach ($projectsData as $p) {
                DB::table('projects')->insert($p);
            }
        }

        // 5. Blogs & Articles
        if (Blog::count() === 0) {
            Blog::insert([
                [
                    'id' => 'blog-1',
                    'title' => 'Why Visakhapatnam is Becoming South India\'s Top Real Estate Investment Destination',
                    'slug' => 'why-visakhapatnam-top-real-estate-investment',
                    'summary' => 'From the upcoming international airport at Bhogapuram to IT corridor expansions, Visakhapatnam offers immense capital appreciation potential.',
                    'excerpt' => 'An in-depth analysis of coastal infrastructure, executive capital growth, and real estate market projections for 2026-2030.',
                    'content' => "<p>Visakhapatnam, the City of Destiny, is undergoing rapid transformation into a world-class economic and maritime hub. With major infrastructure catalysts like the <strong>Bhogapuram Greenfield International Airport</strong>, the expansion of the IT SEZ at Madhurawada, and beach corridor connectivity, property investors are witnessing unprecedented appreciation.</p><h3>1. Strategic Infrastructure Catalysts</h3><p>The connectivity between Madhurawada, Rushikonda, and the new airport has cut travel times by 40%. Prime gated communities and high-rise apartments in these corridors have delivered 18% annual return on investment over the last three years.</p><h3>2. High Quality of Life & Clean Environment</h3><p>Surrounded by picturesque Eastern Ghats hills on one side and the Bay of Bengal on the other, Vizag offers scenic living with clean air quality, reputed educational institutions, and healthcare centers.</p>",
                    'category' => 'Market Trends',
                    'author' => 'Apex Infra Research Team',
                    'image' => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
                    'coverImage' => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
                    'date' => 'September 22, 2026',
                    'tags' => json_encode(['Visakhapatnam', 'Real Estate', 'Investment', 'Bhogapuram']),
                    'readTime' => '5 min read',
                    'published' => true,
                    'publishedAt' => now(),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'blog-2',
                    'title' => 'The Smart Investor\'s Guide to Buying RERA & DTCP Approved Open Plots',
                    'slug' => 'investors-guide-rera-dtcp-open-plots',
                    'summary' => 'Essential legal due-diligence checklist when buying open residential plots for maximum security and peace of mind.',
                    'excerpt' => 'Learn how to verify layout approvals, 14% open space reservations, title encumbrance certificates, and spot registration guidelines.',
                    'content' => "<p>Investing in open plots has always been considered one of the highest-yield wealth generation assets in Indian real estate. However, ensuring clean legal title and statutory compliance is critical.</p><h3>Key Checkpoints Before Investing:</h3><ul><li><strong>RERA Registration:</strong> Ensure the promoter has active RERA approval with a verified project registration number.</li><li><strong>Layout Approval (DTCP / CRDA / VMRDA):</strong> Confirm that public open spaces, 40-ft roads, and underground utility conduits have been formally mortgaged and cleared.</li><li><strong>Nil Encumbrance Certificate (EC):</strong> Always verify a 30-year EC to ensure clear ancestral title without litigation.</li></ul>",
                    'category' => 'Buyer Advice',
                    'author' => 'Legal Cell, Apex Infra',
                    'image' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
                    'coverImage' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
                    'date' => 'September 15, 2026',
                    'tags' => json_encode(['Plots', 'RERA', 'Legal Due Diligence', 'CRDA']),
                    'readTime' => '4 min read',
                    'published' => true,
                    'publishedAt' => now(),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'blog-3',
                    'title' => 'Green Buildings & Sustainable Architecture: What Modern Home Buyers Want in 2026',
                    'slug' => 'green-buildings-sustainable-architecture-2026',
                    'summary' => 'How solar power, rainwater harvesting, and EV charging points are redefining modern apartment living standards.',
                    'excerpt' => 'Discover how energy-efficient construction practices reduce carbon footprints while cutting monthly maintenance bills by 30%.',
                    'content' => "<p>Sustainable living is no longer an optional luxury—it is a core requirement for contemporary homebuyers. At Apex Infra, we incorporate green building design into every foundation.</p><p>With smart rainwater percolation sumps, solar panels powering community common lighting, and EV charging points at each private parking bay, our communities offer long-term cost savings alongside ecological responsibility.</p>",
                    'category' => 'Architecture',
                    'author' => 'Apex Architecture Team',
                    'image' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
                    'coverImage' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
                    'date' => 'September 08, 2026',
                    'tags' => json_encode(['Green Homes', 'Sustainability', 'Solar', 'Eco Friendly']),
                    'readTime' => '6 min read',
                    'published' => true,
                    'publishedAt' => now(),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 6. Gallery Items
        if (GalleryItem::count() === 0) {
            GalleryItem::insert([
                [
                    'id' => 'gal-1',
                    'title' => 'Apex One Heights - Exterior Elevation Dusk View',
                    'category' => 'Exterior',
                    'type' => 'image',
                    'url' => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
                    'imageUrl' => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
                    'thumbnail' => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=400&q=80',
                    'projectAssociation' => 'Apex One Heights',
                    'isMarketing' => false,
                    'date' => '2026-09-20',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'gal-2',
                    'title' => 'Luxury Living Lounge & Double-Height Balcony',
                    'category' => 'Interior',
                    'type' => 'image',
                    'url' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
                    'imageUrl' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
                    'thumbnail' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=400&q=80',
                    'projectAssociation' => 'Apex One Heights',
                    'isMarketing' => false,
                    'date' => '2026-09-19',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'gal-3',
                    'title' => 'Apex Boulevard Beachside Triplex Villa Facade',
                    'category' => 'Exterior',
                    'type' => 'image',
                    'url' => 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
                    'imageUrl' => 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
                    'thumbnail' => 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=400&q=80',
                    'projectAssociation' => 'Apex Boulevard Villas',
                    'isMarketing' => false,
                    'date' => '2026-09-18',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'gal-4',
                    'title' => 'Infinity Swimming Pool & Rooftop Clubhouse Deck',
                    'category' => 'Amenities',
                    'type' => 'image',
                    'url' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
                    'imageUrl' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
                    'thumbnail' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=400&q=80',
                    'projectAssociation' => 'Apex One Heights',
                    'isMarketing' => false,
                    'date' => '2026-09-17',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'gal-5',
                    'title' => 'CRDA Capital City Plot Layout Development Work',
                    'category' => 'Construction',
                    'type' => 'image',
                    'url' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
                    'imageUrl' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
                    'thumbnail' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=400&q=80',
                    'projectAssociation' => 'Apex Capital City Open Plots',
                    'isMarketing' => false,
                    'date' => '2026-09-16',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'gal-6',
                    'title' => 'Apex Horizon Commercial Tower Entrance Grand Lobby',
                    'category' => 'Commercial',
                    'type' => 'image',
                    'url' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
                    'imageUrl' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
                    'thumbnail' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=400&q=80',
                    'projectAssociation' => 'Apex Horizon Commercial Plaza',
                    'isMarketing' => true,
                    'date' => '2026-09-15',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 7. Enquiries / Leads (Project & Marketing)
        if (Enquiry::count() === 0) {
            Enquiry::insert([
                [
                    'id' => 'enq-1',
                    'name' => 'Suresh Kumar Reddy',
                    'email' => 'suresh.reddy@gmail.com',
                    'phone' => '+91 9849123456',
                    'project' => 'Apex One Heights',
                    'projectName' => 'Apex One Heights',
                    'projectAssociation' => 'Apex One Heights',
                    'propertyType' => '3 BHK',
                    'message' => 'Interested in 3 BHK flat on 8th or higher floor facing East. Please share pricing and payment schedule.',
                    'status' => 'Contacted',
                    'date' => '2026-09-24',
                    'notes' => 'Customer visited site with family. Follow-up scheduled on Saturday for booking token.',
                    'isMarketing' => false,
                    'agentId' => 'ag-1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'enq-2',
                    'name' => 'Dr. Ananya Rao',
                    'email' => 'dr.ananya.cardio@apollo.org',
                    'phone' => '+91 9988776655',
                    'project' => 'Apex Boulevard Villas',
                    'projectName' => 'Apex Boulevard Villas',
                    'projectAssociation' => 'Apex Boulevard Villas',
                    'propertyType' => 'Villa',
                    'message' => 'Looking for corner 4 BHK triplex villa with beach view. Need details on handover timeline.',
                    'status' => 'In Progress',
                    'date' => '2026-09-23',
                    'notes' => 'Sent customized PDF quotation and video walkthrough.',
                    'isMarketing' => false,
                    'agentId' => 'ag-1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'enq-3',
                    'name' => 'Ravi Teja Chowdhary',
                    'email' => 'raviteja.c@yahoo.com',
                    'phone' => '+91 9700112233',
                    'project' => 'Apex Capital City Open Plots',
                    'projectName' => 'Apex Capital City Open Plots',
                    'projectAssociation' => 'Apex Capital City Open Plots',
                    'propertyType' => 'Plots',
                    'message' => 'Interested in 200 to 250 Sq.Yard East facing plot near Amaravati highway.',
                    'status' => 'Closed',
                    'date' => '2026-09-20',
                    'notes' => 'Plot #42 booked with initial advance payment of ₹5,00,000.',
                    'isMarketing' => false,
                    'agentId' => 'ag-3',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'enq-4',
                    'name' => 'Kavitha Menon',
                    'email' => 'kavitha.menon@techcorp.in',
                    'phone' => '+91 9885544332',
                    'project' => 'Apex Crystal Towers',
                    'projectName' => 'Apex Crystal Towers',
                    'projectAssociation' => 'Apex Crystal Towers',
                    'propertyType' => '4 BHK',
                    'message' => 'Relocating to Hyderabad Financial District. Need sky villa floor plans.',
                    'status' => 'New',
                    'date' => '2026-09-25',
                    'notes' => 'Lead received via website enquiry modal.',
                    'isMarketing' => false,
                    'agentId' => 'ag-2',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'enq-5',
                    'name' => 'M. Srinivas',
                    'email' => 'srinivas.m@retailventures.com',
                    'phone' => '+91 9848011223',
                    'project' => 'Apex Horizon Commercial Plaza',
                    'projectName' => 'Apex Horizon Commercial Plaza',
                    'projectAssociation' => 'Apex Horizon Commercial Plaza',
                    'propertyType' => 'Commercial',
                    'message' => 'Looking for 1,200 Sft ground-floor retail showroom space on Benz Circle.',
                    'status' => 'Contacted',
                    'date' => '2026-09-22',
                    'notes' => 'Commercial lease proposal sent.',
                    'isMarketing' => true,
                    'agentId' => 'ag-3',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 8. Site Visits
        if (SiteVisit::count() === 0) {
            SiteVisit::insert([
                [
                    'id' => 'sv-1',
                    'customerName' => 'Suresh Kumar Reddy',
                    'customerPhone' => '+91 9849123456',
                    'customerEmail' => 'suresh.reddy@gmail.com',
                    'projectAssociation' => 'Apex One Heights',
                    'projectName' => 'Apex One Heights',
                    'visitDate' => '2026-09-28',
                    'visitTime' => '10:30 AM',
                    'emailStatus' => 'Sent',
                    'emailSentDate' => '2026-09-24',
                    'assignedAgent' => 'Rajesh Varma',
                    'assignedAgentPhone' => '+91 9848022334',
                    'status' => 'Confirmed',
                    'location' => 'Apex One Heights Site Office, Madhurawada',
                    'notes' => 'Client requested to inspect 4th floor model flat sample finishes.',
                    'reminderSent' => true,
                    'feedback' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'sv-2',
                    'customerName' => 'Dr. Ananya Rao',
                    'customerPhone' => '+91 9988776655',
                    'customerEmail' => 'dr.ananya.cardio@apollo.org',
                    'projectAssociation' => 'Apex Boulevard Villas',
                    'projectName' => 'Apex Boulevard Villas',
                    'visitDate' => '2026-09-29',
                    'visitTime' => '04:00 PM',
                    'emailStatus' => 'Sent',
                    'emailSentDate' => '2026-09-24',
                    'assignedAgent' => 'Rajesh Varma',
                    'assignedAgentPhone' => '+91 9848022334',
                    'status' => 'Scheduled',
                    'location' => 'Rushikonda Villa Strip',
                    'notes' => 'High-priority VIP site visit. Arrange site vehicle pickup.',
                    'reminderSent' => false,
                    'feedback' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'sv-3',
                    'customerName' => 'Ravi Teja Chowdhary',
                    'customerPhone' => '+91 9700112233',
                    'customerEmail' => 'raviteja.c@yahoo.com',
                    'projectAssociation' => 'Apex Capital City Open Plots',
                    'projectName' => 'Apex Capital City Open Plots',
                    'visitDate' => '2026-09-18',
                    'visitTime' => '11:00 AM',
                    'emailStatus' => 'Sent',
                    'emailSentDate' => '2026-09-17',
                    'assignedAgent' => 'K. Venkat Rao',
                    'assignedAgentPhone' => '+91 9989077889',
                    'status' => 'Completed',
                    'location' => 'Amaravati Highway Site Gate',
                    'notes' => 'Inspected Plot #40-45. Client satisfied with 60ft road approach.',
                    'reminderSent' => true,
                    'feedback' => 'Booked plot #42 spot on.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 9. Document Storage
        if (Document::count() === 0) {
            Document::insert([
                [
                    'id' => 'doc-1',
                    'title' => 'Apex One Heights - Master Plan & GVMC Building Approval Order',
                    'category' => 'Approvals',
                    'fileUrl' => '/uploads/branding/apex_infra_logo.jpg',
                    'fileSize' => '4.8 MB',
                    'fileType' => 'PDF',
                    'projectAssociation' => 'Apex One Heights',
                    'uploadedBy' => 'Chief Architect',
                    'date' => '2026-08-14',
                    'sortOrder' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'doc-2',
                    'title' => 'AP RERA Official Registration Certificate - Apex One Heights',
                    'category' => 'Legal',
                    'fileUrl' => '/uploads/branding/apex_infra_logo.jpg',
                    'fileSize' => '2.1 MB',
                    'fileType' => 'PDF',
                    'projectAssociation' => 'Apex One Heights',
                    'uploadedBy' => 'Legal Department',
                    'date' => '2026-07-20',
                    'sortOrder' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'doc-3',
                    'title' => 'Soil Investigation & Geo-Technical Structural Safety Report',
                    'category' => 'Technical',
                    'fileUrl' => '/uploads/branding/apex_infra_logo.jpg',
                    'fileSize' => '6.4 MB',
                    'fileType' => 'PDF',
                    'projectAssociation' => 'Apex Boulevard Villas',
                    'uploadedBy' => 'Structural Consultant',
                    'date' => '2026-06-10',
                    'sortOrder' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'doc-4',
                    'title' => 'Standard Customer Agreement of Sale & Allotment Template',
                    'category' => 'Contracts',
                    'fileUrl' => '/uploads/branding/apex_infra_logo.jpg',
                    'fileSize' => '1.5 MB',
                    'fileType' => 'PDF',
                    'projectAssociation' => 'Apex One Heights',
                    'uploadedBy' => 'Admin Officer',
                    'date' => '2026-08-01',
                    'sortOrder' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 10. Job Applications
        if (JobApplication::count() === 0) {
            JobApplication::insert([
                [
                    'id' => 'app-1',
                    'position' => 'Senior Civil Project Engineer',
                    'name' => 'Vikramaditya Patnaik',
                    'applicantName' => 'Vikramaditya Patnaik',
                    'email' => 'vikram.patnaik@civilworks.com',
                    'phone' => '+91 9848033445',
                    'experience' => '7 Years',
                    'resumeUrl' => '/uploads/branding/apex_infra_logo.jpg',
                    'coverLetter' => 'Experienced in supervising high-rise RCC residential towers (G+15) with strict quality control, BBS reinforcement checking, and contractor coordination.',
                    'status' => 'Shortlisted',
                    'date' => '2026-09-21',
                    'notes' => 'Technical interview scheduled with Project Director.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'app-2',
                    'position' => 'Assistant Sales Manager (Real Estate)',
                    'name' => 'Deepika Sundaram',
                    'applicantName' => 'Deepika Sundaram',
                    'email' => 'deepika.s@outlook.com',
                    'phone' => '+91 9700223344',
                    'experience' => '4 Years',
                    'resumeUrl' => '/uploads/branding/apex_infra_logo.jpg',
                    'coverLetter' => 'Proven track record in luxury residential closing, channel partner network management, and HNI client relationship nurturing in Visakhapatnam & Hyderabad.',
                    'status' => 'Interviewed',
                    'date' => '2026-09-18',
                    'notes' => 'Offered position with ₹65,000 monthly CTC + sales incentive structure.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 11. Wallets (Digital, Bank & Petty Cash)
        if (Wallet::count() === 0) {
            Wallet::insert([
                [
                    'id' => 'wal-1',
                    'name' => 'HDFC Project Escrow A/C (Apex One)',
                    'openingBalance' => 10000000,
                    'currentBalance' => 14250000,
                    'type' => 'Bank',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'wal-2',
                    'name' => 'State Bank of India Operational A/C',
                    'openingBalance' => 5000000,
                    'currentBalance' => 4825000,
                    'type' => 'Bank',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'wal-3',
                    'name' => 'Site Petty Cash Wallet - Vizag Site',
                    'openingBalance' => 500000,
                    'currentBalance' => 215000,
                    'type' => 'Cash',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'wal-4',
                    'name' => 'Online Gateway Razorpay & UPI',
                    'openingBalance' => 2000000,
                    'currentBalance' => 1875000,
                    'type' => 'Digital',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 12. Wallet Transactions
        if (WalletTransaction::count() === 0) {
            WalletTransaction::insert([
                [
                    'id' => 'wtx-1',
                    'walletId' => 'wal-1',
                    'toWalletId' => null,
                    'type' => 'CREDIT',
                    'amount' => 2500000,
                    'date' => '2026-09-22',
                    'paymentMode' => 'NEFT',
                    'referenceNumber' => 'HDFC0092817291',
                    'description' => 'Received Flat 402 Foundation Milestone Payment from Suresh Kumar Reddy',
                    'receiptUrl' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'wtx-2',
                    'walletId' => 'wal-2',
                    'toWalletId' => null,
                    'type' => 'DEBIT',
                    'amount' => 845000,
                    'date' => '2026-09-21',
                    'paymentMode' => 'RTGS',
                    'referenceNumber' => 'SBIN992817299',
                    'description' => 'Paid Tata Tiscon TMT Rebar Invoice #TT-884 to Stockist',
                    'receiptUrl' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'wtx-3',
                    'walletId' => 'wal-3',
                    'toWalletId' => null,
                    'type' => 'DEBIT',
                    'amount' => 45000,
                    'date' => '2026-09-23',
                    'paymentMode' => 'Cash',
                    'referenceNumber' => 'CASH-VOUCHER-142',
                    'description' => 'Site water tanker supply & JCB earth mover diesel charges',
                    'receiptUrl' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 13. Customers
        if (Customer::count() === 0) {
            Customer::insert([
                [
                    'id' => 'cust-1',
                    'name' => 'Suresh Kumar Reddy',
                    'mobile' => '+91 9849123456',
                    'email' => 'suresh.reddy@gmail.com',
                    'address' => 'Flat 402, Apex One Heights, Madhurawada, Visakhapatnam',
                    'gstNumber' => null,
                    'creditLimit' => 10000000,
                    'openingBalance' => 8500000,
                    'outstandingAmount' => 6000000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'cust-2',
                    'name' => 'Dr. Ananya Rao',
                    'mobile' => '+91 9988776655',
                    'email' => 'dr.ananya.cardio@apollo.org',
                    'address' => 'Villa 12, Apex Boulevard Villas, Rushikonda, Visakhapatnam',
                    'gstNumber' => null,
                    'creditLimit' => 30000000,
                    'openingBalance' => 24000000,
                    'outstandingAmount' => 14000000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'cust-3',
                    'name' => 'Ravi Teja Chowdhary',
                    'mobile' => '+91 9700112233',
                    'email' => 'raviteja.c@yahoo.com',
                    'address' => 'Plot 42, Apex Capital City, Amaravati Highway',
                    'gstNumber' => null,
                    'creditLimit' => 5000000,
                    'openingBalance' => 5600000,
                    'outstandingAmount' => 2100000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'cust-4',
                    'name' => 'Venkateswara Infra Solutions Pvt Ltd',
                    'mobile' => '+91 9848011223',
                    'email' => 'accounts@venkateswarainfra.com',
                    'address' => 'Showroom C-104, Apex Horizon Commercial Plaza, Vijayawada',
                    'gstNumber' => '37AAACV9876K1Z9',
                    'creditLimit' => 15000000,
                    'openingBalance' => 12000000,
                    'outstandingAmount' => 4000000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 14. Suppliers
        if (Supplier::count() === 0) {
            Supplier::insert([
                [
                    'id' => 'sup-1',
                    'name' => 'UltraTech Cement Depot & Logistics',
                    'contactNumber' => '+91 9848111222',
                    'address' => 'Plot 18, Industrial Estate, Autonagar, Visakhapatnam',
                    'gstNumber' => '37AACCT1234F1Z1',
                    'openingBalance' => 1500000,
                    'outstandingAmount' => 420000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'sup-2',
                    'name' => 'Tata Tiscon TMT Steel Stockist',
                    'contactNumber' => '+91 9988223344',
                    'address' => 'Iron & Hardware Yard, Gajuwaka, Visakhapatnam',
                    'gstNumber' => '37AAACT5678K1Z5',
                    'openingBalance' => 2500000,
                    'outstandingAmount' => 845000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'sup-3',
                    'name' => 'Kajaria Ceramics & Vitrified Tiles Hub',
                    'contactNumber' => '+91 9885445566',
                    'address' => 'Main Road, Benz Circle, Vijayawada',
                    'gstNumber' => '37AAACK1122D1Z8',
                    'openingBalance' => 800000,
                    'outstandingAmount' => 180000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'sup-4',
                    'name' => 'Schneider Electric & Havells Wiring Agency',
                    'contactNumber' => '+91 9866556677',
                    'address' => 'Subhash Road, Daba Gardens, Visakhapatnam',
                    'gstNumber' => '37AABCS3344L1Z2',
                    'openingBalance' => 500000,
                    'outstandingAmount' => 95000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 15. Stock & Inventory Items
        if (InventoryItem::count() === 0) {
            InventoryItem::insert([
                [
                    'id' => 'inv-1',
                    'name' => 'UltraTech Premium OPC 53 Grade Cement',
                    'code' => 'CEM-OPC-53',
                    'category' => 'Raw Materials',
                    'brand' => 'UltraTech',
                    'unit' => 'Bags',
                    'openingStock' => 1500,
                    'purchasePrice' => 385,
                    'sellingPrice' => 430,
                    'gstPercentage' => 28,
                    'currentStock' => 1250,
                    'minimumStockLevel' => 300,
                    'supplierName' => 'UltraTech Cement Depot & Logistics',
                    'warehouseLocation' => 'Apex One Heights Site Godown',
                    'type' => 'Product',
                    'hsn' => '252329',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'inv-2',
                    'name' => 'Tata Tiscon 12mm FE 550D TMT Steel Rebar',
                    'code' => 'STL-TMT-12MM',
                    'category' => 'Steel & Metals',
                    'brand' => 'Tata Tiscon',
                    'unit' => 'Tons',
                    'openingStock' => 35.0,
                    'purchasePrice' => 64500,
                    'sellingPrice' => 69000,
                    'gstPercentage' => 18,
                    'currentStock' => 28.5,
                    'minimumStockLevel' => 5.0,
                    'supplierName' => 'Tata Tiscon TMT Steel Stockist',
                    'warehouseLocation' => 'Central Steel Yard',
                    'type' => 'Product',
                    'hsn' => '721420',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'inv-3',
                    'name' => 'Tata Tiscon 16mm FE 550D TMT Steel Rebar',
                    'code' => 'STL-TMT-16MM',
                    'category' => 'Steel & Metals',
                    'brand' => 'Tata Tiscon',
                    'unit' => 'Tons',
                    'openingStock' => 42.0,
                    'purchasePrice' => 64200,
                    'sellingPrice' => 68800,
                    'gstPercentage' => 18,
                    'currentStock' => 34.0,
                    'minimumStockLevel' => 5.0,
                    'supplierName' => 'Tata Tiscon TMT Steel Stockist',
                    'warehouseLocation' => 'Central Steel Yard',
                    'type' => 'Product',
                    'hsn' => '721420',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'inv-4',
                    'name' => 'AAC Thermal Light Weight Blocks (600x200x150mm)',
                    'code' => 'BLK-AAC-150',
                    'category' => 'Masonry',
                    'brand' => 'Magicrete',
                    'unit' => 'Pcs',
                    'openingStock' => 6000,
                    'purchasePrice' => 62,
                    'sellingPrice' => 74,
                    'gstPercentage' => 12,
                    'currentStock' => 4800,
                    'minimumStockLevel' => 1000,
                    'supplierName' => 'UltraTech Cement Depot & Logistics',
                    'warehouseLocation' => 'Apex One Heights Site Godown',
                    'type' => 'Product',
                    'hsn' => '681011',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'inv-5',
                    'name' => 'Kajaria 800x1200mm Glazed Vitrified Tiles (Statwario)',
                    'code' => 'TIL-KAJ-80120',
                    'category' => 'Finishing',
                    'brand' => 'Kajaria',
                    'unit' => 'Boxes',
                    'openingStock' => 1000,
                    'purchasePrice' => 950,
                    'sellingPrice' => 1200,
                    'gstPercentage' => 18,
                    'currentStock' => 850,
                    'minimumStockLevel' => 150,
                    'supplierName' => 'Kajaria Ceramics & Vitrified Tiles Hub',
                    'warehouseLocation' => 'Finishing Materials Bay',
                    'type' => 'Product',
                    'hsn' => '690721',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 16. Stock Movements
        if (StockMovement::count() === 0) {
            StockMovement::insert([
                [
                    'id' => 'sm-1',
                    'productCode' => 'CEM-OPC-53',
                    'type' => 'ISSUE',
                    'quantity' => 250,
                    'date' => '2026-09-22',
                    'warehouse' => 'Apex One Heights Site Godown',
                    'notes' => 'Issued for 5th floor casting slab concrete pouring',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'sm-2',
                    'productCode' => 'STL-TMT-12MM',
                    'type' => 'ISSUE',
                    'quantity' => 6.5,
                    'date' => '2026-09-20',
                    'warehouse' => 'Central Steel Yard',
                    'notes' => 'Beams reinforcement fabrication for Block-A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 17. Expense Categories
        if (ExpenseCategory::count() === 0) {
            ExpenseCategory::insert([
                ['id' => 'ec-1', 'name' => 'Raw Construction Materials', 'description' => 'Cement, Steel, Sand, Blocks, Aggregates', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'ec-2', 'name' => 'Subcontractor & Labor Charges', 'description' => 'Civil work, shuttering, electrical, plumbing', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'ec-3', 'name' => 'Heavy Machinery & Fuel', 'description' => 'JCB, crane, concrete pump rentals and diesel', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'ec-4', 'name' => 'Statutory Fees & Approvals', 'description' => 'GVMC, VMRDA, CRDA, AP RERA, Electricity deposit', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'ec-5', 'name' => 'Marketing & Digital Advertising', 'description' => 'Hoardings, Google Ads, Meta Ads, Property Portals', 'created_at' => now(), 'updated_at' => now()],
                ['id' => 'ec-6', 'name' => 'Site Office & Admin Overhead', 'description' => 'Staff travel, client refreshments, site electricity', 'created_at' => now(), 'updated_at' => now()],
            ]);
        }

        // 18. Expenses
        if (Expense::count() === 0) {
            Expense::insert([
                [
                    'id' => 'exp-1',
                    'expenseNo' => 'EXP-2026-081',
                    'party' => 'Tata Tiscon TMT Steel Stockist',
                    'expenseCategory' => 'Raw Construction Materials',
                    'billDate' => '2026-09-21',
                    'paymentType' => 'Bank Transfer',
                    'walletId' => 'wal-2',
                    'accountName' => 'State Bank of India Operational A/C',
                    'referenceNo' => 'RTGS-992817299',
                    'roundOff' => true,
                    'totalAmount' => 845000,
                    'paidAmount' => 845000,
                    'pendingAmount' => 0,
                    'paymentStatus' => 'Paid',
                    'projectName' => 'Apex One Heights',
                    'notes' => '13.1 MT 12mm & 16mm FE 550D TMT consignment delivery',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'exp-2',
                    'expenseNo' => 'EXP-2026-082',
                    'party' => 'Sree Rama Ready Mix Concrete (RMC)',
                    'expenseCategory' => 'Raw Construction Materials',
                    'billDate' => '2026-09-22',
                    'paymentType' => 'Bank Transfer',
                    'walletId' => 'wal-1',
                    'accountName' => 'HDFC Project Escrow A/C (Apex One)',
                    'referenceNo' => 'NEFT-881729112',
                    'roundOff' => true,
                    'totalAmount' => 420000,
                    'paidAmount' => 420000,
                    'pendingAmount' => 0,
                    'paymentStatus' => 'Paid',
                    'projectName' => 'Apex One Heights',
                    'notes' => 'M30 Grade ready-mix concrete 85 cubic meters for 5th floor slab',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'exp-3',
                    'expenseNo' => 'EXP-2026-083',
                    'party' => 'GVMC Town Planning Department',
                    'expenseCategory' => 'Statutory Fees & Approvals',
                    'billDate' => '2026-09-15',
                    'paymentType' => 'Demand Draft',
                    'walletId' => 'wal-2',
                    'accountName' => 'State Bank of India Operational A/C',
                    'referenceNo' => 'DD-44120938',
                    'roundOff' => true,
                    'totalAmount' => 210000,
                    'paidAmount' => 210000,
                    'pendingAmount' => 0,
                    'paymentStatus' => 'Paid',
                    'projectName' => 'Apex One Heights',
                    'notes' => 'Betterment charges and road widening inspection compliance fee',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'exp-4',
                    'expenseNo' => 'EXP-2026-084',
                    'party' => 'Signpost Outdoor Media Ltd',
                    'expenseCategory' => 'Marketing & Digital Advertising',
                    'billDate' => '2026-09-10',
                    'paymentType' => 'Bank Transfer',
                    'walletId' => 'wal-2',
                    'accountName' => 'State Bank of India Operational A/C',
                    'referenceNo' => 'NEFT-55192831',
                    'roundOff' => true,
                    'totalAmount' => 150000,
                    'paidAmount' => 150000,
                    'pendingAmount' => 0,
                    'paymentStatus' => 'Paid',
                    'projectName' => 'Apex One Heights',
                    'notes' => 'VIP Road & Beach Road backlit LED hoardings campaign for festive launch',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 19. Quotations
        if (Quotation::count() === 0) {
            Quotation::insert([
                [
                    'id' => 'qtn-1',
                    'quotationNumber' => 'QTN-2026-001',
                    'customerName' => 'Suresh Kumar Reddy',
                    'customerMobile' => '+91 9849123456',
                    'customerAddress' => 'Visakhapatnam, Andhra Pradesh',
                    'date' => '2026-09-15',
                    'validTillDate' => '2026-10-15',
                    'projectName' => 'Apex One Heights',
                    'totalAmount' => 8925000,
                    'status' => 'Accepted',
                    'notes' => 'Includes 2 dedicated basement car parking slots and lifetime club membership.',
                    'termsAndConditions' => '1. Price inclusive of basic structure cost and car parking.\n2. Stamp duty, registration and GST extra at actuals.\n3. Payment according to construction linked milestones.',
                    'items' => json_encode([
                        [
                            'productName' => 'Flat 402 (3 BHK Sky Residence - 1,850 Sft)',
                            'productCode' => 'FLAT-3BHK-402',
                            'quantity' => 1850,
                            'unitPrice' => 4500,
                            'discount' => 0,
                            'gstPercentage' => 5,
                            'total' => 8325000
                        ],
                        [
                            'productName' => 'Covered Basement Double Car Parking',
                            'productCode' => 'AMN-PARK-DBL',
                            'quantity' => 1,
                            'unitPrice' => 400000,
                            'discount' => 0,
                            'gstPercentage' => 0,
                            'total' => 400000
                        ],
                        [
                            'productName' => 'Clubhouse & Infinity Pool Lifetime Membership',
                            'productCode' => 'AMN-CLUB-LIFE',
                            'quantity' => 1,
                            'unitPrice' => 200000,
                            'discount' => 0,
                            'gstPercentage' => 0,
                            'total' => 200000
                        ],
                    ]),
                    'amenityItems' => json_encode([
                        ['name' => 'Generator Backup (3 KVA)', 'cost' => 100000],
                        ['name' => 'Water Sump & Solar Water Connection', 'cost' => 100000]
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'qtn-2',
                    'quotationNumber' => 'QTN-2026-002',
                    'customerName' => 'Dr. Ananya Rao',
                    'customerMobile' => '+91 9988776655',
                    'customerAddress' => 'Apollo Hospitals Campus, Health City, Vizag',
                    'date' => '2026-09-18',
                    'validTillDate' => '2026-10-18',
                    'projectName' => 'Apex Boulevard Villas',
                    'totalAmount' => 24500000,
                    'status' => 'Sent',
                    'notes' => 'Beachside Villa 12 with private plunge pool and home lift.',
                    'termsAndConditions' => 'Handover with turnkey Italian marble finishes within 14 months.',
                    'items' => json_encode([
                        [
                            'productName' => 'Villa 12 (4 BHK Luxury Triplex - 3,400 Sft Built-up Area)',
                            'productCode' => 'VILLA-TRIPLEX-12',
                            'quantity' => 3400,
                            'unitPrice' => 7000,
                            'discount' => 0,
                            'gstPercentage' => 5,
                            'total' => 23800000
                        ],
                        [
                            'productName' => 'Private Heated Plunge Pool & Deck',
                            'productCode' => 'AMN-POOL-PVT',
                            'quantity' => 1,
                            'unitPrice' => 700000,
                            'discount' => 0,
                            'gstPercentage' => 0,
                            'total' => 700000
                        ],
                    ]),
                    'amenityItems' => json_encode([]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 20. Invoices
        if (Invoice::count() === 0) {
            Invoice::insert([
                [
                    'id' => 'inv-doc-1',
                    'invoiceNumber' => 'INV-2026-101',
                    'customerName' => 'Suresh Kumar Reddy',
                    'customerMobile' => '+91 9849123456',
                    'customerAddress' => 'Visakhapatnam, Andhra Pradesh',
                    'projectName' => 'Apex One Heights',
                    'date' => '2026-09-22',
                    'totalAmount' => 2500000,
                    'gstAmount' => 125000,
                    'discountAmount' => 0,
                    'paidAmount' => 2500000,
                    'pendingAmount' => 0,
                    'paymentStatus' => 'Paid',
                    'notes' => 'Received via NEFT #HDFC0092817291 into HDFC Escrow Account.',
                    'termsAndConditions' => 'Official tax receipt for construction installment milestone.',
                    'quotationNumber' => 'QTN-2026-001',
                    'items' => json_encode([
                        [
                            'productName' => 'Booking Token & Foundation Completion Milestone (Flat 402)',
                            'productCode' => 'MILESTONE-FOUNDATION',
                            'quantity' => 1,
                            'price' => 2500000,
                            'discount' => 0,
                            'gst' => 125000,
                            'gstPercentage' => 5,
                            'total' => 2500000
                        ]
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'inv-doc-2',
                    'invoiceNumber' => 'INV-2026-102',
                    'customerName' => 'Ravi Teja Chowdhary',
                    'customerMobile' => '+91 9700112233',
                    'customerAddress' => 'Amaravati, Guntur District',
                    'projectName' => 'Apex Capital City Open Plots',
                    'date' => '2026-09-20',
                    'totalAmount' => 3500000,
                    'gstAmount' => 0,
                    'discountAmount' => 0,
                    'paidAmount' => 3500000,
                    'pendingAmount' => 0,
                    'paymentStatus' => 'Paid',
                    'notes' => 'Paid for Plot #42 (200 Sq.Yards) full registration settlement.',
                    'termsAndConditions' => 'Registration deed executed at Sub-Registrar Office.',
                    'quotationNumber' => 'QTN-2026-003',
                    'items' => json_encode([
                        [
                            'productName' => 'Apex Capital City Plot #42 (200 Sq.Yards)',
                            'productCode' => 'PLOT-CAPITAL-42',
                            'quantity' => 200,
                            'price' => 17500,
                            'discount' => 0,
                            'gst' => 0,
                            'gstPercentage' => 0,
                            'total' => 3500000
                        ]
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 21. Loans & Borrowings
        if (Loan::count() === 0) {
            Loan::insert([
                [
                    'id' => 'loan-1',
                    'providerName' => 'HDFC Bank Real Estate Commercial Finance',
                    'accountNumber' => 'HDFC-CF-482910482',
                    'type' => 'Project Construction Finance',
                    'amount' => 50000000,
                    'interestRate' => 8.75,
                    'startDate' => '2025-04-01',
                    'endDate' => '2028-03-31',
                    'emiAmount' => 625000,
                    'frequency' => 'Monthly',
                    'paidAmount' => 15000000,
                    'pendingAmount' => 35000000,
                    'nextDueDate' => '2026-10-05',
                    'documentUrl' => '/uploads/branding/apex_infra_logo.jpg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'loan-2',
                    'providerName' => 'State Bank of India Machinery & Equipment Division',
                    'accountNumber' => 'SBI-EQ-110294827',
                    'type' => 'Equipment Loan',
                    'amount' => 4500000,
                    'interestRate' => 9.20,
                    'startDate' => '2025-08-01',
                    'endDate' => '2028-07-31',
                    'emiAmount' => 85000,
                    'frequency' => 'Monthly',
                    'paidAmount' => 2200000,
                    'pendingAmount' => 2300000,
                    'nextDueDate' => '2026-10-10',
                    'documentUrl' => '/uploads/branding/apex_infra_logo.jpg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 22. Loan Payments
        if (LoanPayment::count() === 0) {
            LoanPayment::insert([
                [
                    'id' => 'lp-1',
                    'loanId' => 'loan-1',
                    'paymentDate' => '2026-09-05',
                    'amount' => 625000,
                    'principalComponent' => 375000,
                    'interestComponent' => 250000,
                    'paymentMethod' => 'Bank Auto-Debit',
                    'referenceNumber' => 'HDFC-ACH-98217',
                    'reference' => 'HDFC-ACH-98217',
                    'walletId' => 'wal-1',
                    'accountName' => 'HDFC Project Escrow A/C (Apex One)',
                    'isInterestOnly' => false,
                    'notes' => 'Monthly loan tranche interest and principal amortization',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 23. Payments In
        if (PaymentIn::count() === 0) {
            PaymentIn::insert([
                [
                    'id' => 'pin-1',
                    'customerName' => 'Suresh Kumar Reddy',
                    'invoiceNumber' => 'INV-2026-101',
                    'paymentDate' => '2026-09-22',
                    'amount' => 2500000,
                    'paymentMethod' => 'Bank Transfer (NEFT)',
                    'walletId' => 'wal-1',
                    'accountName' => 'HDFC Project Escrow A/C (Apex One)',
                    'referenceNumber' => 'HDFC0092817291',
                    'receiptNo' => 'REC-2026-042',
                    'status' => 'Used',
                    'unusedAmount' => 0,
                    'notes' => 'Flat 402 installment cleared',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'pin-2',
                    'customerName' => 'Dr. Ananya Rao',
                    'invoiceNumber' => null,
                    'paymentDate' => '2026-09-23',
                    'amount' => 1000000,
                    'paymentMethod' => 'Bank Transfer (RTGS)',
                    'walletId' => 'wal-1',
                    'accountName' => 'HDFC Project Escrow A/C (Apex One)',
                    'referenceNumber' => 'SBIR520260923001',
                    'receiptNo' => 'REC-2026-043',
                    'status' => 'Used',
                    'unusedAmount' => 0,
                    'notes' => 'Booking token advance for Villa 12 Rushikonda',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 24. Payments Out
        if (PaymentOut::count() === 0) {
            PaymentOut::insert([
                [
                    'id' => 'pout-1',
                    'supplierName' => 'Tata Tiscon TMT Steel Stockist',
                    'billNumber' => 'BILL-TT-884',
                    'paymentDate' => '2026-09-21',
                    'amount' => 845000,
                    'paymentMethod' => 'RTGS',
                    'walletId' => 'wal-2',
                    'accountName' => 'State Bank of India Operational A/C',
                    'referenceNumber' => 'SBIN992817299',
                    'receiptNo' => 'VOUCH-OUT-109',
                    'status' => 'Used',
                    'unusedAmount' => 0,
                    'notes' => 'Steel shipment cleared in full',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'pout-2',
                    'supplierName' => 'UltraTech Cement Depot & Logistics',
                    'billNumber' => 'BILL-UTC-501',
                    'paymentDate' => '2026-09-18',
                    'amount' => 450000,
                    'paymentMethod' => 'NEFT',
                    'walletId' => 'wal-2',
                    'accountName' => 'State Bank of India Operational A/C',
                    'referenceNumber' => 'NEFT-88192801',
                    'receiptNo' => 'VOUCH-OUT-110',
                    'status' => 'Used',
                    'unusedAmount' => 0,
                    'notes' => 'Bulk cement delivery for slab casting',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 25. Accounting Activity Log
        if (AccountingActivity::count() === 0) {
            AccountingActivity::insert([
                [
                    'id' => 'act-1',
                    'dateTime' => now()->subDays(2),
                    'module' => 'PAYMENT_IN',
                    'activityType' => 'INSERT',
                    'recordId' => 'pin-1',
                    'amount' => 2500000,
                    'description' => 'Recorded ₹25,00,000 inflow from Suresh Kumar Reddy for Flat 402',
                    'userName' => 'Apex Infra Admin',
                    'userRole' => 'Admin',
                    'ipAddress' => '127.0.0.1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 'act-2',
                    'dateTime' => now()->subDays(3),
                    'module' => 'EXPENSE',
                    'activityType' => 'INSERT',
                    'recordId' => 'exp-1',
                    'amount' => 845000,
                    'description' => 'Recorded steel material disbursement ₹8,45,000 to Tata Tiscon Stockist',
                    'userName' => 'Apex Infra Admin',
                    'userRole' => 'Admin',
                    'ipAddress' => '127.0.0.1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // 26. Project Cost Analysis / Sheet
        if (CostAnalysis::count() === 0) {
            CostAnalysis::insert([
                [
                    'id' => 'ca-1',
                    'projectId' => 'proj-1',
                    'projectName' => 'Apex One Heights',
                    'location' => 'Madhurawada, Visakhapatnam',
                    'date' => '2026-09-20',
                    'siteAreaSqYards' => 3600,
                    'outRateCostPerSqYard' => 25000,
                    'outRateCostTotal' => 90000000,
                    'govtMarketValuePerSqYard' => 15000,
                    'registrationPercentage' => 7.5,
                    'registrationCost' => 4050000,
                    'lrsVudaPercentage' => 14,
                    'lrsVudaCost' => 7560000,
                    'totalLandCost' => 101610000,
                    'gvmcPlanApprovalCost' => 3500000,
                    'tdrPercentage' => 1,
                    'tdrAreaSft' => 12000,
                    'tdrTotalCost' => 4800000,
                    'totalTdrPlanCost' => 8300000,
                    'totalFlatsAreaSft' => 180000,
                    'constructionCostPerSft' => 2400,
                    'totalConstructionCost' => 432000000,
                    'ownerSharePercent' => 40,
                    'builderSharePercent' => 60,
                    'totalProjectCost' => 360500000,
                    'totalSaluableAreaSft' => 108000,
                    'sellingPricePerSft' => 4500,
                    'totalAreaSaluableCost' => 486000000,
                    'amenitiesCostPerUnit' => 250000,
                    'numberOfUnits' => 120,
                    'totalAmenitiesCost' => 30000000,
                    'totalSaleValue' => 516000000,
                    'costPerOneSft' => 3337,
                    'netMarginTotal' => 155500000,
                    'landPurchaseCost' => 90000000,
                    'apcpdclElectricityCost' => 4500000,
                    'constructionCivilCost' => 260000000,
                    'borewellsCost' => 800000,
                    'liftCost' => 6500000,
                    'transformerCost' => 3500000,
                    'waterSumpCost' => 2500000,
                    'generatorCost' => 4000000,
                    'intercomCost' => 800000,
                    'cctvCost' => 1200000,
                    'solarCost' => 3000000,
                    'fireSafetyCost' => 5500000,
                    'architectCost' => 6000000,
                    'supervisionCost' => 4500000,
                    'securityCost' => 1800000,
                    'marketingExpense' => 8500000,
                    'legalRegistrationCost' => 4500000,
                    'contingencyCost' => 10000000,
                    'totalOutflow' => 419200000,
                    'flatSalesEstimate' => 486000000,
                    'commercialSalesEstimate' => 30000000,
                    'totalInflow' => 516000000,
                    'netProfit' => 96800000,
                    'profitMarginPercent' => 18.75,
                    'notes' => 'Feasibility analysis with 60:40 joint development agreement. Highly profitable project with strong projected return on capital.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            ]);
        }

        // 27. Project Inspections / Stage Checklist
        if (ProjectInspection::count() === 0) {
            ProjectInspection::insert([
                [
                    'id' => 'insp-1',
                    'projectId' => 'proj-1',
                    'projectName' => 'Apex One Heights',
                    'builderName' => 'Apex Infra',
                    'location' => 'Madhurawada, Visakhapatnam',
                    'reraNo' => 'AP RERA: P03280014522',
                    'checkedBy' => 'Chief Quality Assurance Auditor',
                    'inspectionDate' => '2026-09-22',
                    'overallProgress' => 68.5,
                    'stages' => json_encode([
                        ['stageName' => 'Soil Investigation & Foundation Piling', 'progress' => 100, 'status' => 'Completed', 'remarks' => 'Load test report certified by Geo-Tech Lab.'],
                        ['stageName' => 'Substructure & Double Basement Slab', 'progress' => 100, 'status' => 'Completed', 'remarks' => 'Waterproofing membranes tested and approved.'],
                        ['stageName' => 'Ground to 4th Floor Superstructure', 'progress' => 100, 'status' => 'Completed', 'remarks' => 'Cube compression tests cleared at 32.5 MPa.'],
                        ['stageName' => '5th to 12th Floor Slabs', 'progress' => 85, 'status' => 'In Progress', 'remarks' => '10th floor shuttering in progress.'],
                        ['stageName' => 'AAC Block Masonry & Brickwork', 'progress' => 60, 'status' => 'In Progress', 'remarks' => 'Completed up to 7th floor.'],
                        ['stageName' => 'Internal & External Sand-Faced Plastering', 'progress' => 45, 'status' => 'In Progress', 'remarks' => 'Internal plastering ongoing.'],
                        ['stageName' => 'Concealed Electrical & Plumbing Conduits', 'progress' => 40, 'status' => 'In Progress', 'remarks' => 'CPVC pipes and conduit boxes fitted up to 6th floor.'],
                        ['stageName' => 'Vitrified Tile Flooring & Dadoing', 'progress' => 20, 'status' => 'Upcoming', 'remarks' => 'Material delivered to site.'],
                        ['stageName' => 'Passenger Elevators & Mechanical', 'progress' => 10, 'status' => 'Upcoming', 'remarks' => 'Elevator shafts ready for rail mounting.'],
                        ['stageName' => 'External Weather-Proof Painting', 'progress' => 0, 'status' => 'Upcoming', 'remarks' => 'Scheduled for Q3 2026.'],
                        ['stageName' => 'Clubhouse & Infinity Swimming Pool', 'progress' => 35, 'status' => 'In Progress', 'remarks' => 'Pool civil structure completed.'],
                        ['stageName' => 'Final Landscaping & Occupancy Handover', 'progress' => 0, 'status' => 'Upcoming', 'remarks' => 'Target Q4 2026.'],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            ]);
        }
    }
}
